# Get the latest build version from here: curl -sSL "https://datagrepper.engineering.redhat.com/raw?topic=/topic/VirtualTopic.eng.ci.redhat-container-image.index.built&delta=400800&contains=pipelines" | jq ".raw_messages[].msg.index"
# Check in all 3 openshift version 1 severe testing and other 2 sanity testing
# https://artifacts.ospqa.com/builds/1.15.0/734617-4.16/ to install operators manually

apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: acceptance-tests-114-on-415-hive-
spec:
  pipelineRef:
    name: acceptance-tests
  params:
    - name: ARCH
      value: "linux/amd64"
    - name: CATALOG_SOURCE      ====> custom-operators: when installing unpublished release (theoretically can be anything)
      value: custom-operators   ===>  redhat-operators  
    - name: CLUSTER_POOL        =====> only for hive
      value: "openstack"
    - name: CLUSTER_NAME
      value: resource-hub       =====>   change it to cluster name
    - name: CLI_TESTS_TYPE
      value: downstream
    - name: INDEX               =======> https://quay.io/repository/openshift-pipeline/redhat-operator-index?tab=tags
      value: "717598"           ======>   change it to correct INDEX
    - name: INSTALLER
      value: "hive"                         ==========>  Change the installer name
    - name: INSTALL_PIPELINES_OPERATOR
      value: "true"
    - name: INSTALL_SERVERLESS_OPERATOR
      value: "true"
    - name: OPERATOR_ENVIRONMENT
      value: pre-stage         -====>  stage       =======> prod
    - name: OPERATOR_VERSION
      value: "1.14.4"          ========> https://quay.io/repository/openshift-pipeline/redhat-operator-index?tab=tags
    - name: TEST_SUITES
      value:
      # - cli-tests-fedora
      - release-tests-versions
      - release-tests-chains
      - release-tests-metrics
      - release-tests-clustertasks
      - release-tests-clustertasks-s2i
      - release-tests-clustertasks-multiarch
      - release-tests-pipelines
      - release-tests-results
      - release-tests-triggers
      - release-tests-triggers-tls
      # - operator-upstream-tests
      # - pipelines-upstream-tests
      # - triggers-upstream-tests
      - release-tests-rbac
      - release-tests-auto-prune
      - release-tests-addon
    - name: TKN_DOWNLOAD_URL
      value: https://mirror.openshift.com/pub/openshift-v4/clients/pipelines/1.13.0/tkn-linux-amd64.tar.gz
  timeouts:
    pipeline: 3h
  workspaces:
    - name: git
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 200Mi
          storageClassName: csi-manila-ceph
